name: latexmk

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [normal, full]
        version: ['2023']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Image Tag and Dockerfile
        run: |
          image_name="${{ secrets.DOCKERHUB_USER }}/latexmk"
          if [ "${{ matrix.flavor }}" == "full" ]; then
            build_file="Dockerfile.full"
            image_versioned_tag=":${{ matrix.version }}-full"
            image_tag=":full"
          else
            build_file="Dockerfile"
            image_versioned_tag=":${{ matrix.version }}"
            image_tag=""
          fi
          echo "build_file=$build_file" >> $GITHUB_ENV
          echo "image_versioned_tag=$image_name$image_versioned_tag" >> $GITHUB_ENV
          echo "image_tag=$image_name$image_tag" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./${{ env.build_file }}
          build-args: |
            YEAR=${{ matrix.version }}
          tags: |
            ${{ env.image_versioned_tag }}
            ${{ env.image_tag }}
          platforms: linux/amd64,linux/arm64/v8
          push: true
